name: Implement CI/CD

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18"
          
      - name: Install deps
        run: npm i
          
      - name: Build app bundle
        run: npm run build

      - name: Deploy Pages
        uses: crazy-max/ghaction-github-pages@v3.2.0
        with:
          build_dir: dist/portfolio
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
